# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0Tzq8c_V9HNeyzx4LALjuBZo1F7NGjN
"""

# Data Processing
import pandas as pd
import numpy as np

# NLP
import nltk
import re
import string

# Download NLP resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

"""# dataset

"""

df = pd.read_csv(
    "amazon_reviews.csv",
    engine="python"
)

print(df.shape)

print(df.columns.tolist())

df.head()

missing = df.isnull().sum()

missing_df = pd.DataFrame({
    'Column': missing.index,
    'Missing Values': missing.values,
    'Missing Percentage': (
        missing.values / len(df) * 100
    ).round(2)
})

missing_df = missing_df.sort_values(
    by='Missing Values',
    ascending=False
)

missing_df

print("Number of Categories:")
print(df['category'].nunique())

print("\nTop 20 Categories:")
print(df['category'].value_counts().head(20))

print(df['rating'].value_counts().sort_index())

# 保留项目需要的字段

df = df[
    [
        'reviewText',
        'rating',
        'category',
        'brand',
        'reviewTime'
    ]
]

print(df.shape)

df.head()

df = df.dropna(
    subset=['reviewText']
)

print(df.shape)

df['brand'] = df['brand'].fillna('Unknown')
df['brand'].isnull().sum()

before = len(df)

df = df.drop_duplicates(
    subset=['reviewText']
)

after = len(df)

print("Removed:", before - after)
print("Remaining:", after)

df.to_csv(
    "clean_reviews_stage1.csv",
    index=False
)

df['category'].value_counts().head(20)

df['rating'].value_counts().sort_index()

"""# true_sentiment"""

def sentiment_label(rating):

    if rating >= 4:
        return "Positive"

    elif rating == 3:
        return "Neutral"

    else:
        return "Negative"

df['true_sentiment'] = (
    df['rating']
    .apply(sentiment_label)
)

df['true_sentiment'].value_counts()

"""# Cleaning"""

import nltk
import re
import string
import pandas as pd

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):

    if pd.isna(text):
        return ""

    # lowercase
    text = text.lower()

    # remove urls
    text = re.sub(r'http\S+|www\S+', '', text)

    # remove html
    text = re.sub(r'<.*?>', '', text)

    # remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # tokenization
    tokens = text.split()

    # stopword removal + lemmatization
    cleaned_tokens = []

    for word in tokens:

        if word not in stop_words:

            lemma = lemmatizer.lemmatize(word)

            if len(lemma) > 1:
                cleaned_tokens.append(lemma)

    return " ".join(cleaned_tokens)

import nltk

nltk.download('punkt_tab')

sample = df['reviewText'].iloc[0]

print("ORIGINAL:")
print(sample)

print("\nCLEANED:")
print(clean_text(sample))

!pip install tqdm

from tqdm import tqdm

tqdm.pandas()

df['cleaned_review'] = (
    df['reviewText']
    .progress_apply(clean_text)
)

df[
    [
        'reviewText',
        'cleaned_review'
    ]
].head(10)

df['review_length'] = (
    df['cleaned_review']
    .str.split()
    .str.len()
)

df[
    [
        'cleaned_review',
        'review_length'
    ]
].head()

df = df.rename(
    columns={
        'reviewText':'original_review',
        'category':'product_category',
        'reviewTime':'review_time'
    }
)

df = df.reset_index(drop=True)

df.insert(
    0,
    'review_id',
    range(1, len(df) + 1)
)

final_df = df[
    [
        'review_id',
        'original_review',
        'cleaned_review',
        'rating',
        'true_sentiment',
        'product_category',
        'brand',
        'review_length',
        'review_time'
    ]
]

print(df.columns.tolist())

print(final_df.shape)

final_df.head()

total_reviews = len(final_df)

positive_reviews = (
    final_df['true_sentiment']
    .eq('Positive')
    .sum()
)

neutral_reviews = (
    final_df['true_sentiment']
    .eq('Neutral')
    .sum()
)

negative_reviews = (
    final_df['true_sentiment']
    .eq('Negative')
    .sum()
)

avg_review_length = (
    final_df['review_length']
    .mean()
)

num_categories = (
    final_df['product_category']
    .nunique()
)

num_brands = (
    final_df['brand']
    .nunique()
)

print(f"Total Reviews: {total_reviews}")
print(f"Positive Reviews: {positive_reviews}")
print(f"Neutral Reviews: {neutral_reviews}")
print(f"Negative Reviews: {negative_reviews}")
print(f"Average Review Length: {avg_review_length:.2f}")
print(f"Number of Categories: {num_categories}")
print(f"Number of Brands: {num_brands}")
print("Train/Test Split Ratio: 80:20")

final_df.sample(10)

final_df.to_csv(
    "final_corpus.csv",
    index=False
)

from google.colab import files

files.download("final_corpus.csv")

final_df = final_df[
    final_df['cleaned_review'].notna()
]

final_df = final_df[
    final_df['cleaned_review'].str.strip() != ''
]
